// <auto-generated />
namespace Hospital_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Surveys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Surveys));
        
        string IMigrationMetadata.Id
        {
            get { return "202107251633019_Surveys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
