// <auto-generated />
namespace Hospital_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class survey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(survey));
        
        string IMigrationMetadata.Id
        {
            get { return "202108122304572_survey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
