// <auto-generated />
namespace Hospital_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_feedback_datatype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_feedback_datatype));
        
        string IMigrationMetadata.Id
        {
            get { return "202108052014149_change_feedback_datatype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
